# Hyperparameters Configuration File
# This file contains all the training and model hyperparameters

# Model Selection
MODEL:
  architecture: yolov8  # Options: yolov8, yolov5, faster-rcnn, ssd
  variant: n  # Options: n (nano), s (small), m (medium), l (large), x (extra-large)
  pretrained: true
  num_classes: 3  # Fire, default, smoke

# Training Hyperparameters
TRAINING:
  epochs: 100
  batch_size: 16
  learning_rate: 0.01
  momentum: 0.937
  weight_decay: 0.0005
  warmup_epochs: 3
  warmup_momentum: 0.8
  warmup_bias_lr: 0.1
  
  # Learning Rate Scheduler
  lr_scheduler: cosine  # Options: cosine, linear, step
  lr_decay_factor: 0.1
  lr_decay_epochs: [70, 90]
  
  # Optimizer
  optimizer: SGD  # Options: SGD, Adam, AdamW
  
  # Early Stopping
  patience: 50  # Stop if no improvement for 50 epochs
  
  # Mixed Precision Training
  amp: true  # Automatic Mixed Precision for faster training
  
  # Multi-GPU Training
  device: 0  # GPU device, or 'cpu' for CPU training
  workers: 8  # Number of dataloader workers

# Data Augmentation Parameters
AUGMENTATION:
  hsv_h: 0.015  # HSV-Hue augmentation
  hsv_s: 0.7    # HSV-Saturation augmentation
  hsv_v: 0.4    # HSV-Value augmentation
  degrees: 0.0  # Rotation (+/- degrees)
  translate: 0.1  # Translation (+/- fraction)
  scale: 0.5    # Scale (+/- gain)
  shear: 0.0    # Shear (+/- degrees)
  perspective: 0.0  # Perspective (+/- fraction)
  flipud: 0.0   # Vertical flip probability
  fliplr: 0.5   # Horizontal flip probability
  mosaic: 1.0   # Mosaic augmentation probability
  mixup: 0.0    # MixUp augmentation probability
  copy_paste: 0.0  # Copy-paste augmentation probability

# Image Processing
IMAGE:
  input_size: 640  # Input image size (square)
  normalize: true
  mean: [0.485, 0.456, 0.406]  # ImageNet mean
  std: [0.229, 0.224, 0.225]   # ImageNet std

# Model Architecture Specific
YOLO:
  conf_threshold: 0.25  # Confidence threshold for predictions
  iou_threshold: 0.45   # IoU threshold for NMS
  max_det: 300          # Maximum detections per image
  
  # Anchor boxes (auto-calculated if not specified)
  anchors: null
  
  # Loss weights
  box_loss_gain: 0.05
  cls_loss_gain: 0.5
  dfl_loss_gain: 1.5

# Validation Parameters
VALIDATION:
  val_split: 0.2  # Validation split if not using separate test set
  save_period: 10  # Save checkpoint every N epochs
  eval_interval: 1  # Evaluate every N epochs
  save_best_only: true
  
# Inference Parameters
INFERENCE:
  confidence_threshold: 0.25
  iou_threshold: 0.45
  max_detections: 100
  agnostic_nms: false  # Class-agnostic NMS
  
# Logging and Monitoring
LOGGING:
  log_interval: 10  # Log every N batches
  save_plots: true
  save_predictions: true
  tensorboard: true
  wandb: false  # Set to true if using Weights & Biases
  wandb_project: fire-smoke-detection
  
# Reproducibility
SEED: 42
deterministic: true
